# Generated by Django 5.1.1 on 2024-10-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitout', '0002_user_verified_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('third_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=9)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('marital_status', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('spouse_name', models.CharField(max_length=50)),
                ('number_of_sons', models.IntegerField(default=0)),
                ('rent_value', models.IntegerField(default=0)),
                ('income_value', models.IntegerField(default=0)),
                ('home_status', models.CharField(max_length=7)),
                ('other_funds', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('health_status', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitout.clientsurvey')),
            ],
        ),
    ]
