# Generated by Django 5.1.1 on 2024-11-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentitout', '0007_itemrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreservation',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemreservation',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemreservation',
            name='receive_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
